### ISSUE TITLE
V2 compatiblity: Error: Token too short

### ISSUE THREAD

**Issue by RodrigoSaka** [domdomegg/rsa-securid-browser-extension#1]
Unfortunately it didn't work with the token you have here:
![image](https://user-images.githubusercontent.com/2762661/99599512-45777c80-29da-11eb-91e9-fa8fd57ce869.png)

**Comment by domdomegg** [comment]
Hi Rodrigo, can you confirm you've generated an android software token and have pasted the full token in?

If you're technical you might be able to try playing with https://github.com/domdomegg/rsa-securid and see if you can figure it out any more info?

**Comment by RodrigoSaka** [comment]
My token is this one, I changed the numbers for security reasons since I use it for work and the RSA Securid app works perfect.
Basically the length of the string is the one below:
http://127.0.0.1/securid/ctf?ctfData=999999999999999999999999999999999999999999999999999999999999999999999999999999999

**Comment by kumar-lakshmanan** [comment]
Facing same issue.
My URL is: 
http://127.0.0.1/securid/ctkip?scheme=https&url=xxxx.xxxxxx.com:1xx3/ctkip/services/CtkipService&activationCode=83xxx8577

**Comment by domdomegg** [comment]
> My token is this one, I changed the numbers for security reasons since I use it for work and the RSA Securid app works perfect.
> Basically the length of the string is the one below:
> http://127.0.0.1/securid/ctf?ctfData=999999999999999999999999999999999999999999999999999999999999999999999999999999999

@RodrigoSaka

I've done some more research and think this may be a V1 or V2 token. This extension requires an Android V3 token.

Is the first digit in the ctfData a 1 or 2? If so, you'll need to generate a new android token - it should start with `AwAA` I believe.

> Facing same issue.
> My URL is:
> http://127.0.0.1/securid/ctkip?scheme=https&url=xxxx.xxxxxx.com:1xx3/ctkip/services/CtkipService&activationCode=83xxx8577

@kaymatrix

This is interesting, that looks like a link which can help in issuing new tokens. This application only works with complete tokens (Compressed Token Format (CTF) rather than Dynamic Seed Provisioning (CT-KIP)). Maybe see if you can generate one of those?

**Comment by RodrigoSaka** [comment]
@domdomegg the first digits are these:
http://127.0.0.1/securid/ctf?ctfData=200041282303467217xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by domdomegg** [comment]
> @domdomegg the first digits are these:
> http://127.0.0.1/securid/ctf?ctfData=200041282303467217xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Ah unfortunately this is a V2 token as it begins with a 2. If possible, try regenerating an Android token to try to get a V3 one. I might take a go at adding V2 support at some point, or you're welcome to submit a PR - just needs to detect the right version by checking the first digit and then call the different method from the library, although V2 tokens have been tested less there.

**Comment by RodrigoSaka** [comment]
> > @domdomegg the first digits are these:
> > http://127.0.0.1/securid/ctf?ctfData=200041282303467217xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> 
> Ah unfortunately this is a V2 token as it begins with a 2. If possible, try regenerating an Android token to try to get a V3 one. I might take a go at adding V2 support at some point, or you're welcome to submit a PR - just needs to detect the right version by checking the first digit and then call the different method from the library, although V2 tokens have been tested less there.

I understood, unfortunately I have no way to generate this token again, I no longer have permission to generate again.

**Comment by domdomegg** [comment]
@RodrigoSaka 

I have updated this extension to better support V2 tokens and submitted the new package for review to Google. It'll take some time to review, but hopefully v1.1.0 should be available for download soon from https://chrome.google.com/webstore/detail/rsa-securid-code-generato/bdkphnndaejdmmbohpejmlfejfdbepap

If you want it even faster, you can following the instructions in the README to install manually.

Also I must warn you that it may still not work with your V2 token, but at least you can try it out and see.

**Comment by nmelay** [comment]
v1.1.0 doesn't work here with my V2 token.
Did anyone confirm success with this change?

**Comment by nmelay** [comment]
I was able to convert my V2 token to V3 using [Kevin Cernekee](https://github.com/cernekee)'s [stoken](https://github.com/cernekee/stoken) software.

**Comment by domdomegg** [comment]
Hi nmelay, thanks for the feedback. Could you confirm:
1. What error you got with the V2 token
2. Whether after converting it to V3 using stoken you were able to use it with the browser extension?

For context, this Chrome extension uses the [rsa-securid library](https://www.npmjs.com/package/rsa-securid) derived from stoken, so there's probably some bug in the translation there. If you have experience, you could compare the implementation in [stoken](https://github.com/cernekee/stoken/blob/c948387975d1663b362d122ba5f4b8e6771ac716/src/securid.c#L302) and [rsa-securid](https://github.com/domdomegg/rsa-securid/blob/master/src/v2.ts) to spot any differences that might be causing the problem.

**Comment by nmelay** [comment]
Hi Adam,

1. With V2 token I got the same error RodrigoSaka reported, "Error: Token too short".
2. Yes, the extension works perfectly fine with the converted V3 token.

No I won't investigate further sorry, this is way beyond my knowledge and ability.  :-P

**Comment by domdomegg** [comment]
Thanks @nmelay, I'll review this and see whether I can figure out what's going on here.
